require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('./backend/models/Question');

const questions = [

  // ─────────────────────────────────────────────
  // CLASS 1-3 : LOGICAL REASONING
  // ─────────────────────────────────────────────
  { classGroup:'1-3', subject:'logical', question:'Which number comes next: 2, 4, 6, 8, __?', options:['9','10','11','12'], answer:1 },
  { classGroup:'1-3', subject:'logical', question:'Which shape has 3 sides?', options:['Circle','Square','Triangle','Rectangle'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'If Monday is the 1st day, what is the 4th day?', options:['Wednesday','Thursday','Friday','Saturday'], answer:1 },
  { classGroup:'1-3', subject:'logical', question:'Which number is the smallest? 5, 3, 8, 1', options:['5','3','8','1'], answer:3 },
  { classGroup:'1-3', subject:'logical', question:'Complete the pattern: 🍎🍊🍎🍊__', options:['🍊','🍎','🍋','🍇'], answer:0 },
  { classGroup:'1-3', subject:'logical', question:'A cat has 4 legs. How many legs do 2 cats have?', options:['6','8','4','10'], answer:1 },
  { classGroup:'1-3', subject:'logical', question:'Which comes after 19?', options:['18','20','21','17'], answer:1 },
  { classGroup:'1-3', subject:'logical', question:'If you have 5 apples and eat 2, how many are left?', options:['2','4','3','7'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'Which is different? Dog, Cat, Bird, Table', options:['Dog','Cat','Bird','Table'], answer:3 },
  { classGroup:'1-3', subject:'logical', question:'What comes next: A B C D __?', options:['F','E','G','H'], answer:1 },
  { classGroup:'1-3', subject:'logical', question:'How many sides does a square have?', options:['3','5','4','6'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'Which number is the biggest? 10, 20, 15, 5', options:['10','5','15','20'], answer:3 },
  { classGroup:'1-3', subject:'logical', question:'If today is Tuesday, what day was yesterday?', options:['Monday','Wednesday','Sunday','Thursday'], answer:0 },
  { classGroup:'1-3', subject:'logical', question:'2 + 3 = ?', options:['4','6','5','7'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'Which is the odd one out? Red, Blue, Apple, Green', options:['Red','Blue','Apple','Green'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'What is half of 10?', options:['3','4','5','6'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'Count the letters in "CAT"', options:['2','4','3','5'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'Which animal is bigger? Mouse or Elephant?', options:['Mouse','Elephant','Both same','Neither'], answer:1 },
  { classGroup:'1-3', subject:'logical', question:'1, 3, 5, 7, __ (what comes next?)', options:['8','10','9','11'], answer:2 },
  { classGroup:'1-3', subject:'logical', question:'A week has how many days?', options:['5','6','7','8'], answer:2 },

  // CLASS 1-3 : ENGLISH
  { classGroup:'1-3', subject:'english', question:'Which word is a fruit?', options:['Chair','Mango','School','Run'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'What is the plural of "cat"?', options:['cates','cats','catt','catss'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'Which letter comes before "D"?', options:['B','C','E','F'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'Pick the correct spelling:', options:['Buk','Book','Bouk','Bok'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'I ___ a student. (Fill in the blank)', options:['is','are','am','be'], answer:2 },
  { classGroup:'1-3', subject:'english', question:'Which word means "happy"?', options:['Sad','Angry','Joyful','Tired'], answer:2 },
  { classGroup:'1-3', subject:'english', question:'How many vowels are in "APPLE"?', options:['1','2','3','4'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'What is the opposite of "big"?', options:['Tall','Small','Round','Long'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'Pick the animal word:', options:['Run','Jump','Lion','Green'], answer:2 },
  { classGroup:'1-3', subject:'english', question:'"She ___ to school every day." Fill in:', options:['go','goes','going','gone'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'Which sentence is correct?', options:['I is happy','I am happy','I are happy','I be happy'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'What colour is the sky on a clear day?', options:['Green','Red','Blue','Yellow'], answer:2 },
  { classGroup:'1-3', subject:'english', question:'Which word rhymes with "cat"?', options:['Dog','Bat','Cup','Sun'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'Pick the correct word: "My ___ is Ravi."', options:['age','name','book','school'], answer:1 },
  { classGroup:'1-3', subject:'english', question:'How many letters are in the alphabet?', options:['24','25','26','27'], answer:2 },

  // CLASS 1-3 : GENERAL KNOWLEDGE
  { classGroup:'1-3', subject:'gk', question:'How many days are there in a week?', options:['5','6','7','8'], answer:2 },
  { classGroup:'1-3', subject:'gk', question:'Which animal gives us milk?', options:['Dog','Cat','Cow','Horse'], answer:2 },
  { classGroup:'1-3', subject:'gk', question:'What colour is a ripe banana?', options:['Red','Green','Blue','Yellow'], answer:3 },
  { classGroup:'1-3', subject:'gk', question:'Which is the largest animal on land?', options:['Lion','Elephant','Giraffe','Tiger'], answer:1 },
  { classGroup:'1-3', subject:'gk', question:'How many months are in a year?', options:['10','11','12','13'], answer:2 },
  { classGroup:'1-3', subject:'gk', question:'What do plants need to make food?', options:['Rain','Sunlight','Wind','Moon'], answer:1 },
  { classGroup:'1-3', subject:'gk', question:'What is the capital of India?', options:['Mumbai','Kolkata','Chennai','New Delhi'], answer:3 },
  { classGroup:'1-3', subject:'gk', question:'Which festival is called the festival of lights?', options:['Holi','Eid','Diwali','Christmas'], answer:2 },
  { classGroup:'1-3', subject:'gk', question:'How many fingers are on one hand?', options:['4','5','6','3'], answer:1 },
  { classGroup:'1-3', subject:'gk', question:'Which vehicle runs on tracks?', options:['Bus','Car','Train','Bicycle'], answer:2 },
  { classGroup:'1-3', subject:'gk', question:'Which planet do we live on?', options:['Mars','Venus','Earth','Jupiter'], answer:2 },
  { classGroup:'1-3', subject:'gk', question:'The national bird of India is:', options:['Sparrow','Peacock','Parrot','Eagle'], answer:1 },
  { classGroup:'1-3', subject:'gk', question:'How many seasons are there in India?', options:['2','3','4','6'], answer:3 },
  { classGroup:'1-3', subject:'gk', question:'Which sense organ do we use to smell?', options:['Eyes','Ears','Nose','Tongue'], answer:2 },
  { classGroup:'1-3', subject:'gk', question:'Which is the tallest mountain in the world?', options:['K2','Everest','Kangchenjunga','Lhotse'], answer:1 },

  // ─────────────────────────────────────────────
  // CLASS 4-5 : LOGICAL REASONING
  // ─────────────────────────────────────────────
  { classGroup:'4-5', subject:'logical', question:'Find the missing number: 3, 6, 12, 24, __', options:['36','48','30','42'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'If all roses are flowers and some flowers are red, which is definitely true?', options:['All roses are red','Some roses are red','All flowers are roses','Roses are not red'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'Which is the odd one out? Apple, Mango, Potato, Banana', options:['Apple','Mango','Potato','Banana'], answer:2 },
  { classGroup:'4-5', subject:'logical', question:'Complete: 2, 5, 10, 17, 26, __', options:['35','37','36','38'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'A clock shows 3:00. The hour hand points to?', options:['12','3','6','9'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'If MANGO = 5 letters, ORANGE = ?', options:['5','6','4','7'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'Rearrange NEAM to form a fruit name:', options:['MENA','MEAN','MANE','AMEN'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'5 × 4 ÷ 2 + 1 = ?', options:['10','11','9','12'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'Which figure can be formed from triangle + square?', options:['Pentagon','House shape','Circle','Hexagon'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'In a line, Ravi is 5th from front and 4th from back. How many in line?', options:['7','8','9','10'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'Find pattern: Z, X, V, T, __', options:['S','R','Q','P'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'If 2 pens cost ₹10, how much do 5 pens cost?', options:['₹20','₹25','₹30','₹15'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'Mirror image: the left hand of a person in a mirror looks like?', options:['Left hand','Right hand','Both look same','No hands'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'Choose the pair: Doctor : Hospital :: Teacher : ?', options:['Book','Student','School','Pen'], answer:2 },
  { classGroup:'4-5', subject:'logical', question:'ABCDE — which is the middle letter?', options:['B','C','D','A'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'1 dozen = ?', options:['10','12','14','20'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'Smallest prime number is:', options:['0','1','2','3'], answer:2 },
  { classGroup:'4-5', subject:'logical', question:'Which shape has no corners?', options:['Square','Triangle','Circle','Rectangle'], answer:2 },
  { classGroup:'4-5', subject:'logical', question:'Sun : Day :: Moon : ?', options:['Star','Night','Sky','Cloud'], answer:1 },
  { classGroup:'4-5', subject:'logical', question:'What fraction of a day is 6 hours?', options:['1/2','1/3','1/4','1/6'], answer:2 },

  // CLASS 4-5 : ENGLISH
  { classGroup:'4-5', subject:'english', question:'Choose the correct sentence:', options:['She go to school','She goes to school','She going to school','She gone to school'], answer:1 },
  { classGroup:'4-5', subject:'english', question:'Opposite of "ancient" is:', options:['Old','Modern','Antique','Aged'], answer:1 },
  { classGroup:'4-5', subject:'english', question:'A group of fish is called a:', options:['Herd','Flock','School','Pack'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Which word is a noun?', options:['Run','Beautiful','Happiness','Quickly'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'"I ___ reading a book." Fill in:', options:['is','are','am','be'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Plural of "child" is:', options:['Childs','Childes','Children','Childrens'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Which is a proper noun?', options:['City','Mountain','India','River'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Synonym of "brave" is:', options:['Fearful','Timid','Courageous','Weak'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Which sentence uses "their" correctly?', options:['Their going home','That is their house','There house is big','They\'re house'], answer:1 },
  { classGroup:'4-5', subject:'english', question:'A word that describes a noun is called:', options:['Verb','Adjective','Adverb','Pronoun'], answer:1 },
  { classGroup:'4-5', subject:'english', question:'Identify the verb: "She quickly ran to school"', options:['She','quickly','ran','school'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Correct spelling:', options:['Recieve','Recive','Receive','Receeve'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'"He is as brave ___ a lion." Fill in:', options:['like','than','as','then'], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Which punctuation ends a question?', options:['.','!','?',','], answer:2 },
  { classGroup:'4-5', subject:'english', question:'Opposite of "expand" is:', options:['Grow','Enlarge','Contract','Increase'], answer:2 },

  // CLASS 4-5 : GK
  { classGroup:'4-5', subject:'gk', question:'Who wrote the Indian National Anthem?', options:['Bankim Chandra','Rabindranath Tagore','Mahatma Gandhi','Sarojini Naidu'], answer:1 },
  { classGroup:'4-5', subject:'gk', question:'The largest continent is:', options:['Africa','Australia','Asia','Europe'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'The process by which plants make food is called:', options:['Digestion','Photosynthesis','Respiration','Absorption'], answer:1 },
  { classGroup:'4-5', subject:'gk', question:'Who is the Father of the Nation of India?', options:['Nehru','Ambedkar','Gandhi','Patel'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'Fastest animal on land:', options:['Lion','Horse','Cheetah','Tiger'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'The sun rises in the:', options:['West','South','East','North'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'National animal of India:', options:['Elephant','Lion','Tiger','Leopard'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'Which gas do we breathe in?', options:['CO2','Nitrogen','Oxygen','Hydrogen'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'Bones in the human body (adult):', options:['206','208','200','204'], answer:0 },
  { classGroup:'4-5', subject:'gk', question:'Olympics are held every ___ years:', options:['2','3','4','5'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'Currency of Japan:', options:['Won','Dollar','Yen','Euro'], answer:2 },
  { classGroup:'4-5', subject:'gk', question:'Smallest continent:', options:['Africa','Antarctica','Europe','Australia'], answer:3 },
  { classGroup:'4-5', subject:'gk', question:'Who invented the telephone?', options:['Edison','Bell','Einstein','Newton'], answer:1 },
  { classGroup:'4-5', subject:'gk', question:'The first Indian to go to space:', options:['Kalpana Chawla','Rakesh Sharma','Sunita Williams','APJ Abdul Kalam'], answer:1 },
  { classGroup:'4-5', subject:'gk', question:'Number of states in India (2024):', options:['28','29','30','31'], answer:0 },

  // ─────────────────────────────────────────────
  // CLASS 6-8 : LOGICAL REASONING
  // ─────────────────────────────────────────────
  { classGroup:'6-8', subject:'logical', question:'If BREAD is coded as EAGBR, how is WATER coded?', options:['RETAW','RAWET','WATIR','EWART'], answer:0 },
  { classGroup:'6-8', subject:'logical', question:'Series: 1, 4, 9, 16, 25, __?', options:['30','35','36','49'], answer:2 },
  { classGroup:'6-8', subject:'logical', question:'Rahul is taller than Mohan. Sonu is shorter than Rahul but taller than Mohan. Who is shortest?', options:['Rahul','Mohan','Sonu','All equal'], answer:1 },
  { classGroup:'6-8', subject:'logical', question:'A and B can do a work in 10 days. B alone in 15 days. A alone in?', options:['20 days','25 days','30 days','35 days'], answer:2 },
  { classGroup:'6-8', subject:'logical', question:'Pointing to a man, a woman says "His mother\'s only daughter is my mother." How is the woman related to the man?', options:['Sister','Niece','Aunt','Daughter'], answer:1 },
  { classGroup:'6-8', subject:'logical', question:'Find missing: 6, 11, 21, 36, 56, __', options:['71','81','91','101'], answer:1 },
  { classGroup:'6-8', subject:'logical', question:'Book : Library :: Painting : ?', options:['Museum','Artist','Gallery','Canvas'], answer:2 },
  { classGroup:'6-8', subject:'logical', question:'Which is the smallest? 3/4, 2/3, 5/6, 7/12', options:['3/4','2/3','5/6','7/12'], answer:3 },
  { classGroup:'6-8', subject:'logical', question:'A train 150m long passes a pole in 15 sec. Its speed is:', options:['10 m/s','8 m/s','12 m/s','15 m/s'], answer:0 },
  { classGroup:'6-8', subject:'logical', question:'How many triangles in a rectangle cut diagonally twice?', options:['2','3','4','5'], answer:2 },
  { classGroup:'6-8', subject:'logical', question:'If 5 + 3 = 28 and 7 + 2 = 63, then 6 + 4 = ?', options:['24','48','42','210'], answer:2 },
  { classGroup:'6-8', subject:'logical', question:'Water : Ice :: Steam : ?', options:['Fire','Cloud','Water','Gas'], answer:2 },
  { classGroup:'6-8', subject:'logical', question:'Complete: CMM, EOO, GQQ, __, KUU', options:['ISS','ITT','HSS','IST'], answer:0 },
  { classGroup:'6-8', subject:'logical', question:'In 2 hours a clock ticks how many times?', options:['120','7200','3600','1440'], answer:1 },
  { classGroup:'6-8', subject:'logical', question:'ODDE is coded as ADDE. Then LXYZ is coded as?', options:['AXYZ','LXYA','AXYA','LXYZ'], answer:0 },
  { classGroup:'6-8', subject:'logical', question:'Average of first 5 multiples of 3:', options:['8','9','10','12'], answer:1 },
  { classGroup:'6-8', subject:'logical', question:'Hospital : Doctor :: Court : ?', options:['Criminal','Judge','Lawyer','Police'], answer:1 },
  { classGroup:'6-8', subject:'logical', question:'What comes next: ACE, BDF, CEG, __?', options:['DFH','DEF','CFG','EFH'], answer:0 },
  { classGroup:'6-8', subject:'logical', question:'If 20% of a number is 50, what is the number?', options:['200','250','300','400'], answer:1 },
  { classGroup:'6-8', subject:'logical', question:'Pointing to a photo: "He is the only son of my grandfather\'s son." The person is the speaker\'s?', options:['Father','Uncle','Cousin','Brother'], answer:3 },

  // CLASS 6-8 : ENGLISH
  { classGroup:'6-8', subject:'english', question:'Identify the figure of speech: "The wind whispered through the trees."', options:['Simile','Metaphor','Personification','Alliteration'], answer:2 },
  { classGroup:'6-8', subject:'english', question:'Choose the correct passive voice: "She wrote a letter."', options:['A letter is written by her','A letter was written by her','A letter has been written','A letter had written by her'], answer:1 },
  { classGroup:'6-8', subject:'english', question:'Synonym of "meticulous":', options:['Careless','Precise','Hasty','Lazy'], answer:1 },
  { classGroup:'6-8', subject:'english', question:'Choose the correctly punctuated sentence:', options:["Its a dog's life","It's a dog's life","Its a dogs life","It\'s a dogs life"], answer:1 },
  { classGroup:'6-8', subject:'english', question:'"Despite the rain, ___ went for a walk." Fill in:', options:['them','they','their','theirs'], answer:1 },
  { classGroup:'6-8', subject:'english', question:'Which is a compound sentence?', options:['She runs fast.','She runs fast and he walks slowly.','Running fast, she won.','She, a fast runner, won.'], answer:1 },
  { classGroup:'6-8', subject:'english', question:'Antonym of "benevolent":', options:['Kind','Generous','Malevolent','Helpful'], answer:2 },
  { classGroup:'6-8', subject:'english', question:'One word for "a person who loves books":', options:['Bibliophile','Bibliophobe','Polyglot','Bibliograph'], answer:0 },
  { classGroup:'6-8', subject:'english', question:'Identify the adverb: "She sang beautifully."', options:['She','sang','beautifully','None'], answer:2 },
  { classGroup:'6-8', subject:'english', question:'"Neither the students nor the teacher ___ present." Fill in:', options:['were','was','are','have'], answer:1 },
  { classGroup:'6-8', subject:'english', question:'Which word is spelled correctly?', options:['Occurance','Occurrence','Occurence','Occurrance'], answer:1 },
  { classGroup:'6-8', subject:'english', question:'The phrase "to let the cat out of the bag" means:', options:['To release a cat','To reveal a secret','To confuse someone','To shop at market'], answer:1 },
  { classGroup:'6-8', subject:'english', question:'What tense is "I had finished my work"?', options:['Simple Past','Present Perfect','Past Perfect','Future Perfect'], answer:2 },
  { classGroup:'6-8', subject:'english', question:'Reading Comprehension — "The boy was sad because he lost his toy." Why was the boy sad?', options:['He was hungry','He was tired','He lost his toy','He fell down'], answer:2 },
  { classGroup:'6-8', subject:'english', question:'Which sentence is in indirect speech? Direct: "I am happy," she said.', options:['She said that she is happy','She said that she was happy','She says that she is happy','She told I am happy'], answer:1 },

  // CLASS 6-8 : GK
  { classGroup:'6-8', subject:'gk', question:'Which planet is known as the Red Planet?', options:['Venus','Saturn','Mars','Jupiter'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'The Great Wall is located in:', options:['India','Japan','China','Korea'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'Who discovered penicillin?', options:['Marie Curie','Louis Pasteur','Alexander Fleming','Joseph Lister'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'The longest river in the world is:', options:['Amazon','Nile','Ganges','Yangtze'], answer:1 },
  { classGroup:'6-8', subject:'gk', question:'Who wrote "Romeo and Juliet"?', options:['Dickens','Shakespeare','Keats','Shelley'], answer:1 },
  { classGroup:'6-8', subject:'gk', question:'India celebrates Independence Day on:', options:['Jan 26','Aug 15','Oct 2','Nov 14'], answer:1 },
  { classGroup:'6-8', subject:'gk', question:'The chemical formula of water is:', options:['H2O2','HO','H2O','O2H'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'The Quit India Movement was launched in:', options:['1930','1942','1947','1920'], answer:1 },
  { classGroup:'6-8', subject:'gk', question:'Headquarters of the United Nations:', options:['Geneva','Paris','New York','London'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'Currency of United Kingdom:', options:['Dollar','Euro','Pound','Franc'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'Who was India\'s first Prime Minister?', options:['Gandhi','Patel','Nehru','Shastri'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'Which gas is most abundant in Earth\'s atmosphere?', options:['Oxygen','Carbon Dioxide','Argon','Nitrogen'], answer:3 },
  { classGroup:'6-8', subject:'gk', question:'The 2024 Olympics were held in:', options:['Tokyo','London','Paris','Los Angeles'], answer:2 },
  { classGroup:'6-8', subject:'gk', question:'ICC Cricket World Cup 2023 winner:', options:['Australia','India','England','New Zealand'], answer:0 },
  { classGroup:'6-8', subject:'gk', question:'Which blood group is called the universal donor?', options:['A','B','AB','O'], answer:3 },

  // ─────────────────────────────────────────────
  // CLASS 9-10 : LOGICAL REASONING
  // ─────────────────────────────────────────────
  { classGroup:'9-10', subject:'logical', question:'If all birds can fly and penguins are birds, which conclusion is valid?', options:['Penguins can fly','Penguins cannot fly','The premise is incorrect','None of these'], answer:2 },
  { classGroup:'9-10', subject:'logical', question:'A 40% discount on ₹500. Selling price?', options:['₹200','₹250','₹300','₹350'], answer:2 },
  { classGroup:'9-10', subject:'logical', question:'Pipes A and B fill a tank in 20 and 30 mins. Together they fill in?', options:['10 mins','12 mins','15 mins','25 mins'], answer:1 },
  { classGroup:'9-10', subject:'logical', question:'A man walks 4 km North then 3 km East. Distance from start?', options:['5 km','7 km','6 km','4 km'], answer:0 },
  { classGroup:'9-10', subject:'logical', question:'Find the next: 2, 3, 5, 8, 13, 21, __', options:['29','33','34','31'], answer:2 },
  { classGroup:'9-10', subject:'logical', question:'If x + y = 10 and xy = 21, then x² + y² = ?', options:['58','100','79','62'], answer:0 },
  { classGroup:'9-10', subject:'logical', question:'A shop marks up by 30% then gives 10% discount. Profit %?', options:['17%','20%','15%','18%'], answer:0 },
  { classGroup:'9-10', subject:'logical', question:'Odd one out: 8, 27, 64, 100, 125', options:['8','27','100','125'], answer:2 },
  { classGroup:'9-10', subject:'logical', question:'Age of father is 3x son. 5 years ago father was 4x son. Son\'s current age?', options:['10','15','12','20'], answer:1 },
  { classGroup:'9-10', subject:'logical', question:'Speed of boat in still water = 10 km/h, current = 2 km/h. Speed downstream?', options:['8 km/h','10 km/h','12 km/h','14 km/h'], answer:2 },
  { classGroup:'9-10', subject:'logical', question:'Blood relation: A is B\'s sister. C is B\'s mother. D is C\'s father. How is A related to D?', options:['Daughter','Granddaughter','Niece','Sister'], answer:1 },
  { classGroup:'9-10', subject:'logical', question:'Which term comes next: 1, 8, 27, 64, 125, __?', options:['196','216','225','256'], answer:1 },
  { classGroup:'9-10', subject:'logical', question:'Simple interest on ₹1000 at 5% per annum for 3 years:', options:['₹100','₹150','₹200','₹50'], answer:1 },
  { classGroup:'9-10', subject:'logical', question:'Calender: Jan 1 2023 is Sunday. What day is Jan 1 2024?', options:['Sunday','Monday','Tuesday','Wednesday'], answer:1 },
  { classGroup:'9-10', subject:'logical', question:'Average of 5 numbers is 20. If one number 30 is replaced by 10, new average?', options:['18','16','14','17'], answer:1 },
  { classGroup:'9-10', subject:'logical', question:'Which is largest? 2/3, 3/4, 4/5, 5/6', options:['2/3','3/4','4/5','5/6'], answer:3 },
  { classGroup:'9-10', subject:'logical', question:'A rectangle\'s length is doubled and width halved. Area change?', options:['Doubles','Halves','Same','Quadruples'], answer:2 },
  { classGroup:'9-10', subject:'logical', question:'Statement: All cats are animals. Some animals are wild. Conclusion?', options:['All cats are wild','Some cats are wild','No cats are wild','Can\'t determine'], answer:3 },
  { classGroup:'9-10', subject:'logical', question:'Code: PENCIL → QFODJM. What is TABLE in the same code?', options:['UBCMF','UABMF','UBALF','UBCLE'], answer:0 },
  { classGroup:'9-10', subject:'logical', question:'In a class of 40, 18 play cricket, 20 play football, 7 play both. How many play neither?', options:['9','7','5','11'], answer:0 },

  // CLASS 9-10 : ENGLISH
  { classGroup:'9-10', subject:'english', question:'Identify the rhetorical device: "It was the best of times, it was the worst of times."', options:['Oxymoron','Paradox','Antithesis','Irony'], answer:2 },
  { classGroup:'9-10', subject:'english', question:'Which sentence is grammatically correct?', options:['Between you and I','Between you and me','Between you and myself','Between I and you'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'Precis writing — choose the best summary of: "The meeting was cancelled due to lack of quorum."', options:['Meeting cancelled — quorum absent','Meeting was long','No one was interested','Meeting postponed'], answer:0 },
  { classGroup:'9-10', subject:'english', question:'Word closest in meaning to "ephemeral":', options:['Eternal','Temporary','Strong','Ancient'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'Correct reported speech: He said, "I will come tomorrow."', options:['He said that he will come tomorrow','He said that he would come the next day','He told that he comes the next day','He said he will come the next day'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'Identify the clause: "Although it rained, we played."', options:['Noun clause','Adjective clause','Adverbial clause','Principal clause'], answer:2 },
  { classGroup:'9-10', subject:'english', question:'Antonym of "indigenous":', options:['Native','Local','Foreign','Original'], answer:2 },
  { classGroup:'9-10', subject:'english', question:'Which is NOT a feature of formal writing?', options:['Use of passive voice','Contractions (don\'t, can\'t)','Third person perspective','Complex vocabulary'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'One word: "one who walks in sleep":', options:['Insomniac','Somnambulist','Narcissist','Altruist'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'"The quality of mercy is not strained." This is from:', options:['Hamlet','Othello','Macbeth','Merchant of Venice'], answer:3 },
  { classGroup:'9-10', subject:'english', question:'Which sentence uses the subjunctive mood correctly?', options:['If I was rich','If I were rich','If I am rich','If I will be rich'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'Reading comprehension: "Despite opposition, she pursued her dream with determination." What does this tell us?', options:['She gave up','She was determined','She had no dreams','She faced no problems'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'Difference between "affect" and "effect": "The noise ___ his concentration."', options:['effected','affected','effects','affects'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'Which is a gerund phrase? ', options:['To run fast','Running fast is fun','He runs fast','Fast running'], answer:1 },
  { classGroup:'9-10', subject:'english', question:'Identify the error: "Neither of the boys have done their homework."', options:['Neither','boys','have','homework'], answer:2 },

  // CLASS 9-10 : GK
  { classGroup:'9-10', subject:'gk', question:'The Preamble of India begins with:', options:['We the Citizens','We the People','We the Indians','We the Sovereign'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'India\'s GDP rank globally (2024):', options:['3rd','4th','5th','6th'], answer:2 },
  { classGroup:'9-10', subject:'gk', question:'PM of India as of 2024:', options:['Manmohan Singh','Rahul Gandhi','Narendra Modi','Amit Shah'], answer:2 },
  { classGroup:'9-10', subject:'gk', question:'G20 Summit 2023 was held in:', options:['China','USA','India','Germany'], answer:2 },
  { classGroup:'9-10', subject:'gk', question:'Which country launched the Chandrayaan-3 mission?', options:['USA','Russia','China','India'], answer:3 },
  { classGroup:'9-10', subject:'gk', question:'The Nobel Prize in Literature 2023 was awarded to:', options:['Annie Ernaux','Jon Fosse','Olga Tokarczuk','Abdulrazak Gurnah'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'Which country has the largest population (2024)?', options:['China','USA','India','Indonesia'], answer:2 },
  { classGroup:'9-10', subject:'gk', question:'Which is NOT a permanent member of UN Security Council?', options:['France','Germany','UK','China'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'India\'s first Chief Justice:', options:['Y.V. Chandrachud','H.J. Kania','B.K. Mukherjea','M.C. Mahajan'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'Formula for speed:', options:['Distance/Time','Time/Distance','Distance×Time','1/2×m×v²'], answer:0 },
  { classGroup:'9-10', subject:'gk', question:'Which Indian won the Booker Prize for "The God of Small Things"?', options:['Jhumpa Lahiri','Arundhati Roy','Kiran Desai','Salman Rushdie'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'What is Article 370?', options:['Right to Education','Special status of J&K (now revoked)','Directive Principles','Fundamental Rights'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'India\'s national sport:', options:['Cricket','Hockey','Football','Kabaddi'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'Gravitational acceleration on Earth:', options:['8.9 m/s²','9.8 m/s²','10.2 m/s²','11 m/s²'], answer:1 },
  { classGroup:'9-10', subject:'gk', question:'Which organ produces insulin?', options:['Liver','Kidney','Pancreas','Heart'], answer:2 },

  // ─────────────────────────────────────────────
  // CLASS 11-12 : LOGICAL REASONING
  // ─────────────────────────────────────────────
  { classGroup:'11-12', subject:'logical', question:'If a:b = 3:5 and b:c = 2:3, then a:b:c is?', options:['6:10:15','3:5:9','3:5:6','6:10:12'], answer:0 },
  { classGroup:'11-12', subject:'logical', question:'Compound interest on ₹10000 at 10% p.a. for 2 years:', options:['₹2000','₹2100','₹1900','₹2200'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'In how many ways can 5 books be arranged on a shelf?', options:['25','60','120','240'], answer:2 },
  { classGroup:'11-12', subject:'logical', question:'A die is thrown. P(prime number)?', options:['1/2','1/3','2/3','1/6'], answer:0 },
  { classGroup:'11-12', subject:'logical', question:'Find the next term: 1, 1, 2, 3, 5, 8, 13, __', options:['18','20','21','23'], answer:2 },
  { classGroup:'11-12', subject:'logical', question:'Venn diagram: 100 students. 60 like Math, 50 like Science, 25 both. How many like neither?', options:['5','10','15','20'], answer:2 },
  { classGroup:'11-12', subject:'logical', question:'Train A passes train B in 18 sec. A is 200m, B is 160m. Together = 360m. Speed relative?', options:['20 m/s','15 m/s','18 m/s','25 m/s'], answer:0 },
  { classGroup:'11-12', subject:'logical', question:'If log₂(8) = x, then x =', options:['2','3','4','8'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'In a group of 6, in how many ways can a president and vice president be chosen?', options:['12','30','36','15'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'Which data structure uses LIFO?', options:['Queue','Tree','Stack','Linked List'], answer:2 },
  { classGroup:'11-12', subject:'logical', question:'Two numbers are in ratio 3:4. Their LCM is 84. The numbers are:', options:['21,28','18,24','12,16','24,32'], answer:0 },
  { classGroup:'11-12', subject:'logical', question:'In a survey: 70% read newspaper A, 60% read B, and 40% read both. What % read at least one?', options:['80%','85%','90%','95%'], answer:2 },
  { classGroup:'11-12', subject:'logical', question:'Missing: 2, 6, 12, 20, 30, __', options:['40','42','44','45'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'Critical thinking: "All politicians are honest" — is this a valid generalisation?', options:['Yes, always','No, hasty generalisation','Yes, based on data','No, false analogy'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'If f(x) = x² + 1, what is f(f(1))?', options:['2','4','5','3'], answer:2 },
  { classGroup:'11-12', subject:'logical', question:'Find HCF of 144 and 180:', options:['18','24','36','48'], answer:2 },
  { classGroup:'11-12', subject:'logical', question:'A coin is tossed 3 times. P(exactly 2 heads)?', options:['1/4','3/8','1/2','1/8'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'Syllogism: All A are B. No B are C. Conclusion?', options:['All A are C','No A are C','Some A are C','Some C are A'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'Work: A finishes in 8 days, B in 12 days. Working together from day 1, A leaves after 2 days. B finishes in?', options:['8 days','7 days','6 days','5 days'], answer:1 },
  { classGroup:'11-12', subject:'logical', question:'Which is the odd one out? NaOH, KOH, HCl, Ca(OH)₂', options:['NaOH','KOH','HCl','Ca(OH)₂'], answer:2 },

  // CLASS 11-12 : ENGLISH
  { classGroup:'11-12', subject:'english', question:'Identify the literary device: "The pen is mightier than the sword."', options:['Hyperbole','Metaphor','Synecdoche','Metonymy'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'Choose the correct sentence:', options:['He has less friends than her','He has fewer friends than her','He has less friend than she','He has fewer friend than her'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'Which word is closest in meaning to "obfuscate"?', options:['Clarify','Confuse','Simplify','Illuminate'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'"To be or not to be" is from Shakespeare\'s:', options:['Macbeth','King Lear','Hamlet','Othello'], answer:2 },
  { classGroup:'11-12', subject:'english', question:'Identify the fallacy: "You\'re wrong because you\'re young."', options:['Straw Man','Ad Hominem','Appeal to Authority','False Dilemma'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'Which is NOT a feature of a research abstract?', options:['Methodology','Results','Conclusion','Literature Review'], answer:3 },
  { classGroup:'11-12', subject:'english', question:'Choose the correct form: "If I ___ the prime minister, I would reduce taxes."', options:['am','was','were','will be'], answer:2 },
  { classGroup:'11-12', subject:'english', question:'Precis — best title for a passage on climate change urgency:', options:['Weather Changes','Climate Crisis Demands Immediate Action','Rain and Sun','Future is Bright'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'One word for "fear of open spaces":', options:['Claustrophobia','Agoraphobia','Acrophobia','Xenophobia'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'Which is an example of stream-of-consciousness writing?', options:['The Odyssey','Ulysses by James Joyce','Pride and Prejudice','Don Quixote'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'"The medium is the message" was coined by:', options:['Noam Chomsky','Marshall McLuhan','Ferdinand de Saussure','Roland Barthes'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'Identify the tone: "Oh, fantastic! Another Monday morning."', options:['Enthusiastic','Sarcastic','Melancholic','Optimistic'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'Correct the error: "The data shows a clear trend."', options:['The datas shows','The data show','The datum shows','No error'], answer:1 },
  { classGroup:'11-12', subject:'english', question:'Which rhetorical appeal uses logic and evidence?', options:['Ethos','Pathos','Logos','Kairos'], answer:2 },
  { classGroup:'11-12', subject:'english', question:'Which sentence best demonstrates parallelism?', options:['She likes running, to swim, and cycling','She likes running, swimming, and cycling','She likes to run, swimming, and cycles','She run, swim and cycle'], answer:1 },

  // CLASS 11-12 : GK
  { classGroup:'11-12', subject:'gk', question:'Which Article of Indian Constitution deals with Right to Equality?', options:['Art 14','Art 19','Art 21','Art 32'], answer:0 },
  { classGroup:'11-12', subject:'gk', question:'ISRO successfully launched Aditya-L1 to study the:', options:['Moon','Mars','Sun','Venus'], answer:2 },
  { classGroup:'11-12', subject:'gk', question:'The Bretton Woods Conference established which institution?', options:['WTO','IMF & World Bank','UNCTAD','G20'], answer:1 },
  { classGroup:'11-12', subject:'gk', question:'AI model GPT-4 was developed by:', options:['Google','Meta','OpenAI','Microsoft'], answer:2 },
  { classGroup:'11-12', subject:'gk', question:'India\'s first indigenously built aircraft carrier:', options:['INS Vikramaditya','INS Vikrant','INS Viraat','INS Arihant'], answer:1 },
  { classGroup:'11-12', subject:'gk', question:'The principle of "Vasudhaiva Kutumbakam" means:', options:['India is great','The world is one family','Education for all','Truth wins'], answer:1 },
  { classGroup:'11-12', subject:'gk', question:'2023 Cricket World Cup was held in:', options:['South Africa','Australia','England','India'], answer:3 },
  { classGroup:'11-12', subject:'gk', question:'Which country hosts the International Court of Justice?', options:['USA','France','Netherlands','Switzerland'], answer:2 },
  { classGroup:'11-12', subject:'gk', question:'The Higgs Boson particle is associated with which laboratory?', options:['NASA','CERN','ISRO','ESA'], answer:1 },
  { classGroup:'11-12', subject:'gk', question:'Union Budget 2024-25: Which ministry has the highest allocation?', options:['Education','Defence','Health','Agriculture'], answer:1 },
  { classGroup:'11-12', subject:'gk', question:'What is the principle behind the UPI payment system?', options:['Blockchain','Real-time gross settlement','Interoperable bank transfer','Cryptocurrency'], answer:2 },
  { classGroup:'11-12', subject:'gk', question:'Who is the author of "The Argumentative Indian"?', options:['Amartya Sen','Shashi Tharoor','Ramachandra Guha','Pankaj Mishra'], answer:0 },
  { classGroup:'11-12', subject:'gk', question:'SDG (Sustainable Development Goals) deadline year:', options:['2025','2030','2035','2040'], answer:1 },
  { classGroup:'11-12', subject:'gk', question:'The term "Stagflation" combines:', options:['Recession + Growth','Inflation + Stagnation','Deflation + Stagflation','Growth + Deflation'], answer:1 },
  { classGroup:'11-12', subject:'gk', question:'National Education Policy 2020 replaced:', options:['NEP 1968','NEP 1986','NEP 1992','NEP 2000'], answer:1 },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  await Question.deleteMany({});
  await Question.insertMany(questions);
  console.log(`Seeded ${questions.length} questions successfully!`);
  mongoose.disconnect();
}

seed().catch(console.error);
